version: '3.5'
services:
  app:
    build: .
    restart: always
    container_name: satelit-api
    #volumes:
    #  - staging-volume:/var/www/html/storage/
    env_file:
      - .env-local

    ports:
      - "80:8080"
volumes:
  staging-volume:
